# Generated by Django 5.2.8 on 2026-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0017_organisation_admin2_organisation_admin3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notify_on_campaign_created',
            field=models.BooleanField(default=True, help_text='Notify all members when a new campaign is launched'),
        ),
        migrations.AddField(
            model_name='group',
            name='notify_on_member_join',
            field=models.BooleanField(default=True, help_text='Notify all members when a new member joins'),
        ),
        migrations.AddField(
            model_name='group',
            name='notify_on_member_promote',
            field=models.BooleanField(default=True, help_text='Notify all members when a member is promoted to admin'),
        ),
        migrations.AddField(
            model_name='group',
            name='notify_on_wallet_transfer',
            field=models.BooleanField(default=True, help_text='Notify all members when a transfer is made from the group wallet'),
        ),
    ]
