# Generated by Django 5.2.8 on 2026-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0018_group_notify_on_campaign_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_disbursement_approvals',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of admin approvals required before a disbursement/transfer executes (1 = any admin can disburse immediately)'),
        ),
    ]
