# Generated by Django 5.2.8 on 2026-08-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0019_group_min_disbursement_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.CharField(choices=[('bereavement', 'Bereavement Fund'), ('excess', 'Insurance Excess Fund'), ('emergency', 'Emergency / Disaster Fundraiser'), ('custom', 'Custom Fund'), ('church', 'Church / Religious Group'), ('stokvel', 'Stokvel & Rotating Savings'), ('student', 'Student Body & Society'), ('sports', 'Sports Club & Team')], default='bereavement', help_text='The primary fund-pooling purpose of this group', max_length=20),
        ),
        migrations.CreateModel(
            name='GroupBereavementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, max_length=150, null=True)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('beneficiary_payout_details', models.TextField(blank=True, help_text='Bank details or mobile money account for payouts', null=True)),
                ('allow_dependents', models.BooleanField(default=True)),
                ('max_dependents', models.PositiveIntegerField(default=5, help_text='Maximum allowed dependents per member')),
                ('allowed_dependent_types', models.CharField(default='Spouse, Child, Parent, Sibling, In-Law', help_text='Comma separated allowed relationships', max_length=255)),
                ('contribution_schedule', models.CharField(choices=[('monthly', 'Monthly Contribution'), ('event_driven', 'Per Bereavement Event'), ('annual', 'Annual Contribution')], default='event_driven', max_length=20)),
                ('fixed_contribution_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fixed_claim_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bereavement_profile', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChurchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_parish_name', models.CharField(blank=True, max_length=150, null=True)),
                ('enable_faith_pledges', models.BooleanField(default=True)),
                ('enable_tax_receipts', models.BooleanField(default=False)),
                ('enable_bulletin_announcements', models.BooleanField(default=True)),
                ('default_tithe_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_profile', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSportsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_category', models.CharField(choices=[('soccer', 'Soccer / Football'), ('rugby', 'Rugby'), ('netball', 'Netball'), ('running_athletics', 'Running & Athletics'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('swimming', 'Swimming'), ('golf', 'Golf'), ('other', 'Other Sport')], default='soccer', max_length=30)),
                ('club_level', models.CharField(choices=[('social_recreational', 'Social & Recreational'), ('amateur_league', 'Amateur League'), ('university_league', 'University League'), ('youth_academy', 'Youth Academy'), ('semi_professional', 'Semi-Professional')], default='social_recreational', max_length=30)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dues_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('per_season', 'Per Season'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('match_fee_per_game', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kit_equipment_fund_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports_profile', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStokvelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stokvel_type', models.CharField(choices=[('rotational_payout', 'Rotational Payout (ROSCA / Mahodisana)'), ('savings_and_investment', 'Savings & Investment'), ('grocery', 'Grocery & Festive Payout'), ('burial', 'Burial Stokvel')], default='rotational_payout', max_length=30)),
                ('cycle_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payout_rotation_mode', models.CharField(choices=[('fixed_sequence', 'Fixed Sequence'), ('random_draw', 'Random Draw'), ('bidding', 'Bidding / Auction'), ('request_on_need', 'Request on Need')], default='fixed_sequence', max_length=20)),
                ('penalty_late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('borrowing_allowed', models.BooleanField(default=False)),
                ('payout_target_month', models.CharField(blank=True, help_text='e.g. December for grocery stokvels', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stokvel_profile', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=150, null=True)),
                ('campus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_body_type', models.CharField(choices=[('residence_committee', 'Residence Committee'), ('faculty_society', 'Faculty & Academic Society'), ('student_representative_council', 'Student Representative Council'), ('sports_res', 'Residence Sports Club'), ('study_group', 'Study & Mutual Aid Group')], default='faculty_society', max_length=35)),
                ('student_id_required', models.BooleanField(default=True, help_text='Require member student registration number')),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('membership_fee_period', models.CharField(choices=[('per_semester', 'Per Semester'), ('annual', 'Annual'), ('once_off', 'Once-off')], default='annual', max_length=20)),
                ('enable_event_ticketing', models.BooleanField(default=True)),
                ('enable_emergency_relief_fund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='chema.group')),
            ],
        ),
    ]
