# Generated by Django 5.2.8 on 2026-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0020_alter_group_purpose_groupbereavementprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
