# Generated by Django 5.2.8 on 2026-08-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0021_groupmembership_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='driver_license_number',
            field=models.CharField(blank=True, help_text='Driver / Owner ID Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='insurer_name',
            field=models.CharField(blank=True, help_text='e.g. Santam / OUTsurance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='vehicle_make_model',
            field=models.CharField(blank=True, help_text='e.g. 2022 Toyota Hilux 2.8 GD-6', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='vehicle_registration',
            field=models.CharField(blank=True, help_text='e.g. CA 987-654', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='vin_number',
            field=models.CharField(blank=True, help_text='Vehicle Identification / Chassis Number', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GroupExcessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_excess_payout', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('require_vin_verification', models.BooleanField(default=True, help_text='Require vehicle VIN/chassis number to prevent fraud')),
                ('require_policy_proof', models.BooleanField(default=True, help_text='Require valid insurance policy number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excess_profile', to='chema.group')),
            ],
        ),
    ]
