# Generated by Django 5.2.8 on 2026-07-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condolence', '0005_campaigncontribution_organisation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaigncontribution',
            unique_together=set(),
        ),
    ]
