# Generated by Django 5.2.8 on 2026-07-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condolence', '0005_campaigncontribution_organisation_and_more'),
        ('wallet', '0008_groupwallettransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwallettransferrequest',
            name='deceased_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transfer_requests', to='condolence.deceased'),
        ),
        migrations.AddField(
            model_name='groupwallettransferrequest',
            name='fund_campaign',
            field=models.ForeignKey(blank=True, help_text='Links this transfer request to a generic FundCampaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_transfer_requests', to='condolence.fundcampaign'),
        ),
    ]
