# Generated by Django 5.2.8 on 2026-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_transaction_idempotency_key_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, help_text='Human-readable purpose/description of this transaction', max_length=512, null=True),
        ),
    ]
