# Generated by Django 5.2.8 on 2026-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_add_note_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwallettransferrequest',
            name='note',
            field=models.TextField(blank=True, help_text='Optional context/reason for this transfer request', null=True),
        ),
    ]
