# Generated by Django 5.2.8 on 2026-08-08 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0019_group_min_disbursement_approvals'),
        ('wallet', '0012_groupwallettransferrequest_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fees_enabled', models.BooleanField(default=True, help_text='Global toggle to enable or disable platform fee collection')),
                ('topup_percentage_fee', models.DecimalField(decimal_places=2, default=2.5, help_text='Top-up percentage fee (%) e.g. 2.50', max_digits=5)),
                ('topup_flat_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat fee per top-up transaction', max_digits=8)),
                ('withdrawal_percentage_fee', models.DecimalField(decimal_places=2, default=1.5, help_text='Withdrawal percentage fee (%) e.g. 1.50', max_digits=5)),
                ('withdrawal_flat_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Flat fee per withdrawal transaction e.g. 5.00', max_digits=8)),
                ('group_transfer_percentage_fee', models.DecimalField(decimal_places=2, default=1.0, help_text='Group disbursement percentage fee (%) e.g. 1.00', max_digits=5)),
                ('group_transfer_flat_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat fee per group disbursement', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Configuration',
                'verbose_name_plural': 'Platform Fee Configuration',
            },
        ),
        migrations.CreateModel(
            name='SMSCreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits_count', models.IntegerField(help_text='Number of SMS notification credits in bundle')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform fee charged on this transaction', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Net amount after deducting platform fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top-Up'), ('TRANSFER', 'Transfer to Group'), ('WITHDRAWAL', 'Withdrawal'), ('PAYOUT_RECEIVED', 'Payout Received'), ('P2P_SENT', 'Peer-to-Peer Sent'), ('P2P_RECEIVED', 'Peer-to-Peer Received'), ('SMS_PACKAGE_PURCHASE', 'SMS Package Purchase')], max_length=20),
        ),
        migrations.CreateModel(
            name='GroupSMSCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_credit_balance', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformFeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('TOP_UP_FEE', 'Top-Up Fee'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('GROUP_TRANSFER_FEE', 'Group Transfer Fee'), ('SMS_PACKAGE_FEE', 'SMS Package Purchase Fee')], max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_fees', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SMSCreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_added', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_purchases', to='chema.group')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.smscreditpackage')),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction')),
            ],
        ),
    ]
