# Generated by Django 5.2.8 on 2026-08-08 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0019_group_min_disbursement_approvals'),
        ('wallet', '0013_platformfeeconfig_smscreditpackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Partner insurance underwriter', max_length=100)),
                ('policy_name', models.CharField(max_length=150)),
                ('cover_amount', models.DecimalField(decimal_places=2, help_text='Total payout coverage ZAR', max_digits=10)),
                ('monthly_premium', models.DecimalField(decimal_places=2, help_text='Monthly premium per member', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FUNERAL_PARLOR', 'Funeral Parlor & Undertaker'), ('CATERING', 'Catering & Event Hire'), ('COUNSELING', 'Mental Health & Counseling'), ('LEGAL_AID', 'Legal Aid & Advisory'), ('WELLNESS', 'Healthcare & Wellness')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='group_pro_monthly_price',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Monthly price for Group Pro tier (ZAR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='is_saas_subscriptions_enabled',
            field=models.BooleanField(default=False, help_text='Phase 2 Toggle: Group SaaS subscriptions & Komunity Plus individual badges'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='is_vendor_marketplace_enabled',
            field=models.BooleanField(default=False, help_text='Phase 3 Toggle: B2B Service Vendor Marketplace & Micro-Insurance products'),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='komunity_plus_monthly_price',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Monthly price for individual Komunity Plus badge (ZAR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformfeeconfig',
            name='vendor_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission % on vendor marketplace bookings', max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformfeeledger',
            name='fee_type',
            field=models.CharField(choices=[('TOP_UP_FEE', 'Top-Up Fee'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('GROUP_TRANSFER_FEE', 'Group Transfer Fee'), ('SMS_PACKAGE_FEE', 'SMS Package Purchase Fee'), ('GROUP_SAAS_FEE', 'Group SaaS Subscription Fee'), ('KOMUNITY_PLUS_FEE', 'Komunity Plus Subscription Fee'), ('VENDOR_COMMISSION_FEE', 'Vendor Marketplace Commission'), ('INSURANCE_COMMISSION_FEE', 'Micro-Insurance Commission')], max_length=30),
        ),
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Group Pro'), ('ENTERPRISE', 'Enterprise / NGO')], default='FREE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='chema.group')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_members_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='chema.group')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wallet.microinsurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('badge_label', models.CharField(default='Komunity Plus Member', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plus_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=255)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chema.group')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wallet.servicevendor')),
            ],
        ),
    ]
