# Generated by Django 5.2.8 on 2026-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_microinsurancepolicy_servicevendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_platform_treasury',
            field=models.BooleanField(default=False, help_text='Flag indicating whether this is the Platform System Treasury Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top-Up'), ('TRANSFER', 'Transfer to Group'), ('WITHDRAWAL', 'Withdrawal'), ('PAYOUT_RECEIVED', 'Payout Received'), ('P2P_SENT', 'Peer-to-Peer Sent'), ('P2P_RECEIVED', 'Peer-to-Peer Received'), ('SMS_PACKAGE_PURCHASE', 'SMS Package Purchase'), ('PLATFORM_FEE_COLLECTED', 'Platform Fee Revenue')], max_length=35),
        ),
    ]
