# Generated by Django 5.2.8 on 2026-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_phoneotp_customuser_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
